frameworks:
  - 'go/gorm'
  - 'haskell/mysql-haskell'
  - 'haskell/mysql-simple'
  - 'haskell/persistent-mysql'
  - 'java/jdbc'
  - 'java/spring'
  - 'javascript/sequelize'
  - 'javascript/typeorm'
  - 'mysqldump/export'
  - 'php/laravel'
  - 'python/django'
  - 'python/PyMySQL'
  - 'python/mysqlclient'
  - 'python/sqlalchemy'
  - 'ruby/rails6'
  - 'rust/diesel'
  - 'rust/mysql'
  - 'rust/mysql_async'
  - 'rust/sqlx'

