name: Pre-merge integration tests
on:
  pull_request:
    branches:
      - master

jobs:
  determine_frameworks:
    name: Get work
    runs-on: ubuntu-latest
    outputs:
      frameworks: ${{ steps.frameworks.outputs.frameworks }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - id: frameworks
        env:
          FILTER_FROM_STDIN: "1"
        run: ./tools/get-frameworks <<<'${{ steps.files.outputs.all }}'

  run_tests:
    name: Frameworks
    runs-on: ubuntu-latest
    needs: determine_frameworks

    services:
      vitess57:
        image: gcr.io/planetscale-vitess-testing/vitess-builder
        ports:
          - 33577:15306
        env:
          VITESS_COMMIT: master
          MYSQL_DIALECT: mysql57
          VT_KEYSPACES: testing:1:0
        options: --privileged --health-cmd="mysqladmin ping -h127.0.0.1 -P15306" --health-start-period=1200s --health-interval=5s --health-timeout=2s --health-retries=5

    strategy:
      fail-fast: false
      matrix:
        framework: ${{ fromJSON(needs.determine_frameworks.outputs.frameworks) }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - id: build
        name: Build changed tests
        run: ./run.sh build_image "${{ matrix.framework }}"

      - id: run-vttestserver57
        name: Run changed tests against vttestserver:mysql57
        run: ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: test
          VT_PASSWORD: test
          VT_DATABASE: testing
          VT_HOST: 127.0.0.1
          VT_PORT: 33577
          VT_NUM_SHARDS: 1
          VT_DIALECT: mysql57

      - id: logs
        name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          images: 'mysql:5.7,mysql:8.0,gcr.io/planetscale-vitess-testing/vitess-builder,vitess/vttestserver:mysql57,vitess/vttestserver:mysql80'

