name: Pre-merge integration tests
on:
  pull_request:
    branches:
      - master

jobs:
  determine_frameworks:
    name: Get work
    runs-on: ubuntu-latest
    outputs:
      frameworks: ${{ steps.frameworks.outputs.frameworks }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - id: frameworks
        env:
          FILTER_FROM_STDIN: "1"
        run: ./tools/get-frameworks <<<'${{ steps.files.outputs.all }}'

  run_tests:
    name: Frameworks
    runs-on: ubuntu-latest
    needs: determine_frameworks

    services:
      mysql57:
        image: mysql:5.7
        ports:
          - 33576:3306
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=5
      mysql80:
        image: mysql:8.0
        ports:
          - 33806:3306
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=5
      vttestserver57:
        image: vitess/vttestserver:mysql57
        ports:
          - 33577:33577
        env:
          PORT: 33574
          KEYSPACES: testing
          NUM_SHARDS: "1"
          MYSQL_BIND_HOST: "0.0.0.0"
        options: --health-cmd="mysqladmin ping -h127.0.0.1 -P33577" --health-interval=5s --health-timeout=2s --health-retries=5
      vttestserver80:
        image: vitess/vttestserver:mysql80
        ports:
          - 33807:33807
        env:
          PORT: 33804
          KEYSPACES: testing
          NUM_SHARDS: "1"
          MYSQL_BIND_HOST: "0.0.0.0"
        options: --health-cmd="mysqladmin ping -h127.0.0.1 -P33807" --health-interval=5s --health-timeout=2s --health-retries=5

    strategy:
      fail-fast: false
      matrix:
        framework: ${{ fromJSON(needs.determine_frameworks.outputs.frameworks) }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - id: fix-mysql80-auth-plugin
        uses: mysql:8.0
        run: mysql -h127.0.0.1 -P33806 -uroot -proot -Ne "ALTER USER root IDENTIFIED WITH mysql_native_password BY 'root'"

      - id: build
        name: Build changed tests
        run: ./run.sh build_image "${{ matrix.framework }}"

      - id: run-mysql57
        name: Run changed tests against upstream MySQL 5.7
        run: ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: testing
          VT_HOST: 127.0.0.1
          VT_PORT: 33576
          VT_DIALECT: mysql57

      - id: run-mysql80
        name: Run changed tests against upstream MySQL 8.0
        run: ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: testing
          VT_HOST: 127.0.0.1
          VT_PORT: 33806
          VT_DIALECT: mysql80

      - id: run-vttestserver57
        name: Run changed tests against vttestserver:mysql57
        run: ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: test
          VT_PASSWORD: test
          VT_DATABASE: testing
          VT_HOST: 127.0.0.1
          VT_PORT: 33577
          VT_DIALECT: mysql57

      - id: run-vttestserver80
        name: Run changed tests against vttestserver:mysql80
        run: ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: test
          VT_PASSWORD: test
          VT_DATABASE: testing
          VT_HOST: 127.0.0.1
          VT_PORT: 33807
          VT_DIALECT: mysql80

      - id: logs
        name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          images: 'mysql:5.7,mysql:8.0,vitess/vttestserver:mysql57,vitess/vttestserver:mysql80'

