name: Full suite of integration tests
on:
  workflow_dispatch:
    inputs:
      vttestserver_tag:
        description: Container image tag for vttestserver
        required: true
        default: "mysql57"

jobs:
  determine_frameworks:
    name: Get work
    runs-on: ubuntu-latest
    outputs:
      frameworks: ${{ steps.frameworks.outputs.frameworks }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: frameworks
        run: ./tools/get-frameworks

  run_tests:
    name: Frameworks
    runs-on: ubuntu-latest
    needs: determine_frameworks

    services:
      vttestserver:
        image: "vitess/vttestserver:${{ github.event.inputs.vttestserver_tag }}"
        ports:
          - 33577:33577
        env:
          PORT: 33574
          KEYSPACES: test
          NUM_SHARDS: "1"
          MYSQL_BIND_HOST: "0.0.0.0"
        options: --health-cmd="mysqladmin ping -h127.0.0.1 -P33577" --health-interval=5s --health-timeout=2s --health-retries=5
    strategy:
      fail-fast: false
      matrix:
        framework: ${{ fromJSON(needs.determine_frameworks.outputs.frameworks) }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - id: pull
        name: Pull tests
        run: ./run.sh pull_image "${{ matrix.framework }}"

      - id: run
        name: Run tests against vttestserver
        run: ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: test
          VT_PASSWORD: test
          VT_DATABASE: test
          VT_HOST: 127.0.0.1
          VT_PORT: 33577

      - id: logs
        name: Dump vttestserver logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          images: 'vitess/vttestserver:mysql57'

