name: Full suite of integration tests
on:
  workflow_dispatch:
    inputs:
      vttestserver57imagetag:
        description: Container image tag to use for vttestserver:mysql57
        default: mysql57
      vttestserver80imagetag:
        description: Container image tag to use for vttestserver:mysql80
        default: mysql80

jobs:
  determine_frameworks:
    name: Get work
    runs-on: ubuntu-latest
    outputs:
      frameworks: ${{ steps.frameworks.outputs.frameworks }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: frameworks
        run: ./tools/get-frameworks

  run_tests:
    name: Frameworks
    runs-on: ubuntu-latest
    needs: determine_frameworks

    services:
      vttestserver57:
        image: "vitess/vttestserver:${{ github.event.inputs.vttestserver57imagetag }}"
        ports:
          - 33577:33577
        env:
          PORT: 33574
          KEYSPACES: test
          NUM_SHARDS: "1"
          MYSQL_BIND_HOST: "0.0.0.0"
        options: --health-cmd="mysqladmin ping -h127.0.0.1 -P33577" --health-interval=5s --health-timeout=2s --health-retries=5
      vttestserver80:
        image: "vitess/vttestserver:${{ github.event.inputs.vttestserver80imagetag }}"
        ports:
          - 33807:33807
        env:
          PORT: 33804
          KEYSPACES: test
          NUM_SHARDS: "1"
          MYSQL_BIND_HOST: "0.0.0.0"
        options: --health-cmd="mysqladmin ping -h127.0.0.1 -P33807" --health-interval=5s --health-timeout=2s --health-retries=5

    strategy:
      fail-fast: false
      matrix:
        framework: ${{ fromJSON(needs.determine_frameworks.outputs.frameworks) }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - id: pull
        name: Pull tests
        run: ./run.sh pull_image "${{ matrix.framework }}"

      - id: run-vttestserver57
        name: Run changed tests against vttestserver:mysql57
        run: ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: test
          VT_PASSWORD: test
          VT_DATABASE: test
          VT_HOST: 127.0.0.1
          VT_PORT: 33577

      - id: run-vttestserver80
        name: Run changed tests against vttestserver:mysql80
        run: ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: test
          VT_PASSWORD: test
          VT_DATABASE: test
          VT_HOST: 127.0.0.1
          VT_PORT: 33807

      - id: logs
        name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          images: 'vitess/vttestserver:${{ github.event.inputs.vttestserver57imagetag }},vitess/vttestserver:${{ github.event.inputs.vttestserver80imagetag }}'

