name: Full suite of integration tests
on:
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Frameworks
    runs-on: ubuntu-latest

    services:
      mysql57:
        image: mysql:5.7
        ports:
          - 33576:3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=5
      vttestserver:
        image: vitess/vttestserver:mysql57
        ports:
          - 33577:33577
        env:
          PORT: 33574
          KEYSPACES: test
          NUM_SHARDS: "1"
          MYSQL_BIND_HOST: "0.0.0.0"
        options: --health-cmd="mysqladmin ping -h127.0.0.1 -P33577" --health-interval=5s --health-timeout=2s --health-retries=5
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        framework:
          - 'go/gorm'
          - 'haskell/mysql-haskell'
          - 'haskell/mysql-simple'
          - 'haskell/persistent-mysql'
          - 'java/jdbc'
          - 'java/spring'
          - 'javascript/sequelize'
          - 'javascript/typeorm'
          - 'mysqldump/export'
          - 'php/laravel'
          - 'python/django'
          - 'python/PyMySQL'
          - 'python/mysqlclient'
          - 'python/sqlalchemy'
          - 'ruby/rails6'
          - 'rust/diesel'
          - 'rust/mysql'
          - 'rust/mysql_async'
          - 'rust/sqlx'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - id: run
        name: Run tests against upstream MySQL 5.7
        run: |
          ./run.sh pull_image "${{ matrix.framework }}"
          ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: root
          VT_PASSWORD: root
          VT_DATABASE: test
          VT_HOST: 127.0.0.1
          VT_PORT: 33576

      - name: Run tests against vttestserver
        run: |
          ./run.sh pull_image "${{ matrix.framework }}"
          ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: test
          VT_PASSWORD: test
          VT_DATABASE: test
          VT_HOST: 127.0.0.1
          VT_PORT: 33577

      - name: Run tests against PSDB
        run: |
          # TODO:  Reuse image from previous step instead of building it again
          ./run.sh build_image "${{ matrix.framework }}"
          ./run.sh run_test "${{ matrix.framework }}"
        env:
          VT_USERNAME: actions
          VT_PASSWORD: ${{ secrets.VT_PASSWORD }}
          VT_DATABASE: itest
          VT_HOST: ${{ secrets.VT_HOST }}
          VT_PORT: 3306

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          images: 'mysql:5.7,vitess/vttestserver:mysql57'

